Fix warnings for Rust 1.85.1 in packages/modules/Virtualization
```
FAILED: out/soong/.intermediates/packages/modules/Virtualization/libs/libfdt/liblibfdt/linux_glibc_x86_64_rlib_rlib-std/liblibfdt.rlib.clippy                                                                                                                                             ANDROID_RUST_VERSION=1.85.1 SOONG_RUST_GEN_DIR=out/soong/.intermediates/packages/modules/Virtualization/libs/libfdt/liblibfdt/linux_glibc_x86_64_rlib_rlib-std/out out/host/linux-x86/bin/rustc_wrapper prebuilts/rust/linux-x86/1.85.1/bin/clippy-driver --emit metadata -o out/soong/.intermediates/packages/modules/Virtualization/libs/libfdt/liblibfdt/linux_glibc_x86_64_rlib_rlib-std/liblibfdt.rlib.clippy --emit dep-info=out/soong/.intermediates/packages/modules/Virtualization/libs/libfdt/liblibfdt/linux_glibc_x86_64_rlib_rlib-std/liblibfdt.rlib.clippy.d.raw packages/modules/Virtualization/libs/libfdt/src/lib.rs --extern static_assertions=out/soong/.intermediates/external/rust/android-crates-io/crates/static_assertions/libstatic_assertions/linux_glibc_x86_64_rlib_rlib-std/libstatic_assertions.rlib --extern libfdt_bindgen=out/soong/.intermediates/packages/modules/Virtualization/libs/libfdt/liblibfdt_bindgen_host/linux_glibc_x86_64_rlib_rlib-std/liblibfdt_bindgen_host.rlib --extern zerocopy=out/soong/.intermediates/external/rust/android-crates-io/crates/zerocopy/libzerocopy/linux_glibc_x86_64_rlib_rlib-std/libzerocopy.rlib --extern std=prebuilts/rust/linux-x86/1.85.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-7db8ef8b6d15f2e7.rlib -L prebuilts/rust/linux-x86/1.85.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/ -L prebuilts/rust/linux-x86/1.85.1/lib/rustlib/x86_64-unknown-linux-gnu/lib -L out/soong/.intermediates/external/rust/android-crates-io/crates/zerocopy-derive/libzerocopy_derive/linux_glibc_x86_64/ -L out/soong/.intermediates/external/dtc/libfdt/libfdt/linux_glibc_x86_64_static/ -Z unstable-options -Z stack-protector=strong -Z remap-cwd-prefix=. -C debuginfo=2 -C opt-level=3 -C overflow-checks=on -C force-unwind-tables=yes -C symbol-mangling-version=v0 --color=always -Z dylib-lto -Z link-native-libraries=no -Z force-unstable-if-unmarked --cfg soong -Lprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/x86_64-linux/lib32 -Lprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/x86_64-linux/lib64 -Lprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/lib/gcc/x86_64-linux/4.8.3 -Lprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/sysroot/usr/lib  -C relocation-model=pic -A deprecated -A unknown_lints -D missing-docs -D warnings -D unsafe_op_in_unsafe_fn --edition=2021 -C metadata=liblibfdt --cfg 'device_assignment' --cfg 'dice_changes' --cfg 'llpvm_changes' --cfg 'network' --cfg 'remote_attestation' --cfg 'vendor_modules' --cfg 'tee_services_allowlist' --cfg 'debuggable_vms_improvements' --cfg 'paravirtualized_devices' --cfg 'long_running_vms' --cfg 'device_assignment' --cfg 'dice_changes' --cfg 'llpvm_changes' --cfg 'network' --cfg 'remote_attestation' --cfg 'vendor_modules' --cfg 'tee_services_allowlist' --cfg 'debuggable_vms_improvements' --cfg 'paravirtualized_devices' --cfg 'long_running_vms' -lstatic:+whole-archive=fdt --crate-type=rlib --crate-name=libfdt --target=x86_64-unknown-linux-gnu --sysroot=/dev/null -C codegen-units=1 -Zallow-features="" -A clippy::disallowed_names -A clippy::empty_line_after_doc_comments -A clippy::type-
complexity -A clippy::unnecessary_fallible_conversions -A clippy::unnecessary-wraps -A clippy::unusual-byte-groupings -A clippy::upper-case-acronyms -D clippy::undocumented_unsafe_blocks && grep ^out/soong/.intermediates/packages/modules/Virtualization/libs/libfdt/liblibfdt/linux_g
libc_x86_64_rlib_rlib-std/liblibfdt.rlib.clippy: out/soong/.intermediates/packages/modules/Virtualization/libs/libfdt/liblibfdt/linux_glibc_x86_64_rlib_rlib-std/liblibfdt.rlib.clippy.d.raw > out/soong/.intermediates/packages/modules/Virtualization/libs/libfdt/liblibfdt/linux_glibc_
x86_64_rlib_rlib-std/liblibfdt.rlib.clippy.d
error: operator precedence can trip the unwary
   --> packages/modules/Virtualization/libs/libfdt/src/iterators.rs:239:34
    |
239 |             AddrCells::Double => (cells.next()? as Self) << 32 | cells.next()? as Self,
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider parenthesizing your expression: `((cells.next()? as Self) << 32) | cells.next()? as Self`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#precedence
    = note: `-D clippy::precedence` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::precedence)]`

error: operator precedence can trip the unwary
   --> packages/modules/Virtualization/libs/libfdt/src/iterators.rs:249:33
    |
249 |                 (cells.next()?, (cells.next()? as u64) << 32 | cells.next()? as u64)
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider parenthesizing your expression: `((cells.next()? as u64) << 32) | cells.next()? as u64`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#precedence

error: operator precedence can trip the unwary
   --> packages/modules/Virtualization/libs/libfdt/src/iterators.rs:264:34
    |
264 |             SizeCells::Double => (cells.next()? as Self) << 32 | cells.next()? as Self,
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider parenthesizing your expression: `((cells.next()? as Self) << 32) | cells.next()? as Self`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#precedence

error: aborting due to 3 previous errors
```

Bug: 421269002
Test: m rust
Flag: EXEMPT refactor
Change-Id: Ic0d7116aa7c2f0c111d9c62efa1c4cca473f5fcd