Make sure that APEXes that go to VM are 4K aligned
Bug: 417114358
Flag: EXEMPT bug fix
Test: intentionally modify 4069 in the change to something else, and
run the VM. The result is as below
Error: Failed to create VM

Caused by:
    Status(-8, EX_SERVICE_SPECIFIC): '-1: Failed to load app config:
APEX com.android.adbd (7950336 bytes) is not aligned to 4K'

Change-Id: Ia722e0b6162ccedc957f02a294f017bece0cb39b