libbssl_avf_error: Add Trusty build rules
This change introduces the necessary `rules.mk` file to enable
building the `libbssl_avf_error` library with the Trusty build
system. This is a dependency for `libservice_vm_comm` and is
required to build the portable RKP TA.

Bug: 467871525
Test: build
Flag: NONE changes applicable to Trusty builds only

Change-Id: I57845903b372885388f85705064fb29ea43787b5