refactor(sign_virt_apex): Error reporting for list mismatches
This change improves the debugging of AVB info mismatches in
`sign_virt_apex.py` by replacing the generic `AssertionError`
with a detailed comparison.

New helper function, `print_descriptors_diff`, is introduced to analyze
the differences and produce a digested result, preventing unhelpful
dumps of large data structures.

Below is an example of the new, detailed error output:

AssertionError: Property descriptor list mismatch for /path/to/microdroid.img:
Original list had 2 descriptors, updated list has 1.

* Common Descriptors (1 items):
  1. com.android.build.system.fingerprint -> 'Baklava/MAIN/...'

* Missing from Updated Descriptors (1 items):
  1. com.android.build.system.os_version -> '16'

Flag: NONE refactoring
Bug: 461370555
Test: atest MicrodroidHostTestCases
Change-Id: I50a8fc6cca4efe562b4859687549435bec0ebc18