refactor(sign_virt_apex): Error reporting for dictionary mismatches
This change improves the debugging of AVB info mismatches in
`sign_virt_apex.py` by replacing the generic `AssertionError`
with a detailed comparison.

New helper function, `print_dict_diff` is introduced to analyze the
differences and produce a digested result, preventing unhelpful dumps
of large data structures.

Below is an example of the new, detailed error output:

AssertionError: Hash descriptor mismatch for/path/to/microdroid_kernel:
Original Hash descriptor had 3 items, updated Hash descriptor has
2 items.

* Common Items (1 items):
  1. ('initrd_normal', {'Image Size': '1281036 bytes',
    'Hash Algorithm': 'sha256', ...})

* Missing from Updated Hash descriptor (1 items):
  1. ('initrd_debug', {'Image Size': '1281200 bytes',
    'Hash Algorithm': 'sha256', ...})

* Modified Items (1 items):
  1. boot: '{'Partition Name': 'boot', 'Flags': '0', ...}' ->
    '{'Partition Name': 'boot', 'Flags': '1', ...}'

Flag: NONE refactoring
Bug: 461370555
Test: atest MicrodroidHostTestCases
Change-Id: I1722577f0f6bc5f8d07b0f70ae2e8d2c4727f39e